# deploy to netlify

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache Hugo program
        id: cache_hugo
        uses: actions/cache@v2
        with:
          path: hugo
          key: ${{ runner.os }}-hugo-${{ hashFiles('website/.hugo_version') }}

      - name: Get Hugo program
        if: steps.cache_hugo.outputs.cache-hit != 'true'
        run: wget https://github.com/keithkoslowsky/binaries/raw/master/hugo.linux.tar.gz; pigz -dc hugo.linux.tar.gz | tar xf -

      - name: Generate files
        run: hugo/hugo.linux -d ../dist -s site -v

      - name: Cache netlify-cli program
        id: cache_netlify-cli
        uses: actions/cache@v2
        with:
          path: netlify-cli
          key: ${{ runner.os }}-netlify-${{ hashFiles('website/.netlify-cli_version') }}

      - name: Get Netlify-CLI program
        if: steps.cache_netlify-cli.outputs.cache-hit != 'true'
        run: wget https://github.com/keithkoslowsky/binaries/raw/master/netlify-cli.tar.gz; pigz -dc netlify-cli.tar.gz | tar xf -

      - name: Deploy to Netlify
        run: netlify-cli/node_modules/netlify-cli/bin/run deploy --dir=dist --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
